[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "snake_game_server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
]

[project.scripts]
snake_game_server = "snake_game_server.__main__:run"

[tool.setuptools.packages.find]
where = ["src"]